/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as AdminAdminRouteImport } from './routes/admin/_admin'
import { Route as AdminAdminIndexRouteImport } from './routes/admin/_admin/index'
import { Route as ApiGithubWriteRouteImport } from './routes/api/github.write'
import { Route as ApiGithubReadRouteImport } from './routes/api/github.read'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth.me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth.logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth.login'
import { Route as ApiAuthInitRouteImport } from './routes/api/auth.init'
import { Route as ApiAuthChangePasswordRouteImport } from './routes/api/auth.change-password'
import { Route as AdminAdminProdutosRouteImport } from './routes/admin/_admin/produtos'
import { Route as AdminAdminLoginRouteImport } from './routes/admin/_admin/login'
import { Route as AdminAdminDashboardRouteImport } from './routes/admin/_admin/dashboard'
import { Route as AdminAdminConfiguracoesRouteImport } from './routes/admin/_admin/configuracoes'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProdutosRoute,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const ApiGithubWriteRoute = ApiGithubWriteRouteImport.update({
  id: '/api/github/write',
  path: '/api/github/write',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubReadRoute = ApiGithubReadRouteImport.update({
  id: '/api/github/read',
  path: '/api/github/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthInitRoute = ApiAuthInitRouteImport.update({
  id: '/api/auth/init',
  path: '/api/auth/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthChangePasswordRoute = ApiAuthChangePasswordRouteImport.update({
  id: '/api/auth/change-password',
  path: '/api/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminProdutosRoute = AdminAdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminLoginRoute = AdminAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminConfiguracoesRoute = AdminAdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/api/analytics': typeof ApiAnalyticsRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/produtos': typeof AdminAdminProdutosRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/init': typeof ApiAuthInitRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/github/read': typeof ApiGithubReadRoute
  '/api/github/write': typeof ApiGithubWriteRoute
  '/admin/': typeof AdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/produtos': typeof AdminAdminProdutosRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/init': typeof ApiAuthInitRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/github/read': typeof ApiGithubReadRoute
  '/api/github/write': typeof ApiGithubWriteRoute
  '/admin': typeof AdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/admin/_admin': typeof AdminAdminRouteWithChildren
  '/api/analytics': typeof ApiAnalyticsRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin/_admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/_admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/_admin/login': typeof AdminAdminLoginRoute
  '/admin/_admin/produtos': typeof AdminAdminProdutosRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/init': typeof ApiAuthInitRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/github/read': typeof ApiGithubReadRoute
  '/api/github/write': typeof ApiGithubWriteRoute
  '/admin/_admin/': typeof AdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/produtos'
    | '/sobre'
    | '/admin'
    | '/api/analytics'
    | '/produtos/$slug'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/produtos'
    | '/api/auth/change-password'
    | '/api/auth/init'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/github/read'
    | '/api/github/write'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/produtos'
    | '/sobre'
    | '/api/analytics'
    | '/produtos/$slug'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/produtos'
    | '/api/auth/change-password'
    | '/api/auth/init'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/github/read'
    | '/api/github/write'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/produtos'
    | '/sobre'
    | '/admin/_admin'
    | '/api/analytics'
    | '/produtos/$slug'
    | '/admin/_admin/configuracoes'
    | '/admin/_admin/dashboard'
    | '/admin/_admin/login'
    | '/admin/_admin/produtos'
    | '/api/auth/change-password'
    | '/api/auth/init'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/github/read'
    | '/api/github/write'
    | '/admin/_admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
  SobreRoute: typeof SobreRoute
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiAuthChangePasswordRoute: typeof ApiAuthChangePasswordRoute
  ApiAuthInitRoute: typeof ApiAuthInitRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiGithubReadRoute: typeof ApiGithubReadRoute
  ApiGithubWriteRoute: typeof ApiGithubWriteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin/': {
      id: '/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/api/github/write': {
      id: '/api/github/write'
      path: '/api/github/write'
      fullPath: '/api/github/write'
      preLoaderRoute: typeof ApiGithubWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/read': {
      id: '/api/github/read'
      path: '/api/github/read'
      fullPath: '/api/github/read'
      preLoaderRoute: typeof ApiGithubReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/init': {
      id: '/api/auth/init'
      path: '/api/auth/init'
      fullPath: '/api/auth/init'
      preLoaderRoute: typeof ApiAuthInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/change-password': {
      id: '/api/auth/change-password'
      path: '/api/auth/change-password'
      fullPath: '/api/auth/change-password'
      preLoaderRoute: typeof ApiAuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin/produtos': {
      id: '/admin/_admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminAdminProdutosRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/login': {
      id: '/admin/_admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminAdminLoginRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/dashboard': {
      id: '/admin/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/configuracoes': {
      id: '/admin/_admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminAdminConfiguracoesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface ProdutosRouteChildren {
  ProdutosSlugRoute: typeof ProdutosSlugRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosSlugRoute: ProdutosSlugRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

interface AdminAdminRouteChildren {
  AdminAdminConfiguracoesRoute: typeof AdminAdminConfiguracoesRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminLoginRoute: typeof AdminAdminLoginRoute
  AdminAdminProdutosRoute: typeof AdminAdminProdutosRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminConfiguracoesRoute: AdminAdminConfiguracoesRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminLoginRoute: AdminAdminLoginRoute,
  AdminAdminProdutosRoute: AdminAdminProdutosRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
  SobreRoute: SobreRoute,
  AdminAdminRoute: AdminAdminRouteWithChildren,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiAuthChangePasswordRoute: ApiAuthChangePasswordRoute,
  ApiAuthInitRoute: ApiAuthInitRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiGithubReadRoute: ApiGithubReadRoute,
  ApiGithubWriteRoute: ApiGithubWriteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
